"""add audit usage and memory candidates

Revision ID: 1708d8d396ac
Revises:
Create Date: 2026-07-16 16:08:40.392331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1708d8d396ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_call_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('call_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('web_search_enabled', sa.String(length=5), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_call_audits_request_id'), 'model_call_audits', ['request_id'], unique=False)
    op.create_index(op.f('ix_model_call_audits_session_id'), 'model_call_audits', ['session_id'], unique=False)
    op.create_index(op.f('ix_model_call_audits_user_id'), 'model_call_audits', ['user_id'], unique=False)
    op.create_table('user_usage_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('chat_requests', sa.Integer(), nullable=False),
    sa.Column('web_search_requests', sa.Integer(), nullable=False),
    sa.Column('model_calls', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='uq_user_usage_daily')
    )
    op.create_table('memory_candidates',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_memories', sa.Column('scope', sa.String(length=20), server_default='global', nullable=False))
    op.alter_column('agent_memories', 'scope', server_default=None)
    op.add_column('agent_memories', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_memories', 'confirmed_at')
    op.drop_column('agent_memories', 'scope')
    op.drop_table('memory_candidates')
    op.drop_table('user_usage_daily')
    op.drop_index(op.f('ix_model_call_audits_user_id'), table_name='model_call_audits')
    op.drop_index(op.f('ix_model_call_audits_session_id'), table_name='model_call_audits')
    op.drop_index(op.f('ix_model_call_audits_request_id'), table_name='model_call_audits')
    op.drop_table('model_call_audits')
    # ### end Alembic commands ###
